# https://circleci.com/docs/2.0/configuration-reference/

version: 2.1
orbs:
  haskell: haskell-works/haskell-build@1.6.6
workflows:
  build-my-application:
    jobs:
      - haskell/build:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
